IP:
  self: '*'
  gs: 192.168.1.123
  uav1: 192.168.1.11
  uav2: 192.168.1.11
  local: 127.0.0.1

recv_topics:
- topic_name: /uav1/mavros/vision_pose/pose
  msg_type: geometry_msgs/PoseStamped
  srcIP: gs
  srcPort: 1102