IP:
  self: '*'
  gs: 192.168.2.101
  uav1: 192.168.2.103
  uav2: 192.168.2.110
  local: 127.0.0.1

send_topics:
- topic_name: /uav1/mavros/vision_pose/pose
  msg_type: geometry_msgs/PoseStamped
  max_freq: 100
  srcIP: self
  srcPort: 1101

- topic_name: /uav2/mavros/vision_pose/pose
  msg_type: geometry_msgs/PoseStamped
  max_freq: 100
  srcIP: self
  srcPort: 1102

- topic_name: /uav3/mavros/vision_pose/pose
  msg_type: geometry_msgs/PoseStamped
  max_freq: 100
  srcIP: self
  srcPort: 1103
